"""
AYRA Ollama Client
------------------
Handles communication between AYRA Brain and Ollama.

Responsibilities:
    - Check Ollama availability
    - Check whether the configured model exists
    - Send chat requests
    - Parse Ollama responses
    - Handle Ollama connection errors

This module does NOT:
    - Build prompts
    - Manage memory
    - Clean responses
    - Handle STT/TTS
"""


import time
import requests


class OllamaClient:
    """
    Client for communicating with a local Ollama server.
    """

    def __init__(self, settings):
        """
        Initialize the Ollama client.

        Args:
            settings: AYRA Settings object.
        """

        self.url = settings.ollama_url
        self.model = settings.ollama_model

        self.context_size = settings.context_size
        self.max_tokens = settings.max_tokens
        self.temperature = settings.temperature

        self.request_timeout = settings.request_timeout
        self.keep_alive = settings.keep_alive

    # ---------------------------------------------------------
    # CONNECTION CHECK
    # ---------------------------------------------------------

    def check_connection(self):
        """
        Check whether Ollama is running and the configured
        model is available.

        Returns:
            bool: True if Ollama and the model are available.
        """

        try:
            response = requests.get(
                f"{self.url}/api/tags",
                timeout=5
            )

            response.raise_for_status()

            data = response.json()

            models = [
                model.get("name", "")
                for model in data.get("models", [])
            ]

            model_exists = any(
                model == self.model
                or model.startswith(f"{self.model}:")
                for model in models
            )

            if not model_exists:

                print(
                    f"AYRA WARNING: "
                    f"Model '{self.model}' was not found."
                )

                print(
                    f"Run: ollama pull {self.model}"
                )

                return False

            print(
                f"✓ Ollama connected | Model: {self.model}"
            )

            return True

        except requests.exceptions.ConnectionError:

            print(
                "✗ Ollama server is not running."
            )

            print(
                "Start it with: ollama serve"
            )

            return False

        except requests.exceptions.Timeout:

            print(
                "✗ Ollama connection timed out."
            )

            return False

        except requests.exceptions.RequestException as exc:

            print(
                f"✗ Ollama connection failed: {exc}"
            )

            return False

        except Exception as exc:

            print(
                f"✗ Ollama check failed "
                f"({type(exc).__name__}): {exc}"
            )

            return False

    # ---------------------------------------------------------
    # CHAT
    # ---------------------------------------------------------

    def chat(self, messages):
        """
        Send messages to Ollama and return the generated text.

        Args:
            messages (list):
                Ollama-compatible chat messages.

        Returns:
            str: Raw response generated by the model.

        Raises:
            requests.exceptions.RequestException:
                If the HTTP request fails.
            RuntimeError:
                If Ollama returns an invalid response.
        """

        start = time.perf_counter()

        try:

            response = requests.post(
                f"{self.url}/api/chat",

                json={
                    "model": self.model,

                    "messages": messages,

                    "stream": False,

                    "keep_alive": self.keep_alive,

                    "options": {
                        "temperature": self.temperature,
                        "num_predict": self.max_tokens,
                        "num_ctx": self.context_size
                    }
                },

                timeout=self.request_timeout
            )

            response.raise_for_status()

            data = response.json()

            message = data.get("message", {})

            content = message.get(
                "content",
                ""
            )

            # Some models may return thinking separately.
            if not content:
                content = message.get(
                    "thinking",
                    ""
                )

            content = str(content).strip()

            elapsed = time.perf_counter() - start

            # -------------------------------------------------
            # PERFORMANCE INFORMATION
            # -------------------------------------------------

            eval_count = data.get(
                "eval_count",
                0
            )

            eval_duration = data.get(
                "eval_duration",
                0
            )

            load_duration = data.get(
                "load_duration",
                0
            )

            if eval_duration:

                eval_seconds = eval_duration / 1_000_000_000

                if eval_seconds > 0 and eval_count:

                    tokens_per_second = (
                        eval_count / eval_seconds
                    )

                    print(
                        f"LLM: {elapsed:.2f}s | "
                        f"{eval_count} tokens | "
                        f"{tokens_per_second:.1f} tok/s"
                    )

                else:

                    print(
                        f"LLM: {elapsed:.2f}s"
                    )

            else:

                print(
                    f"LLM: {elapsed:.2f}s"
                )

            if load_duration:

                load_seconds = (
                    load_duration /
                    1_000_000_000
                )

                print(
                    f"Model load: {load_seconds:.2f}s"
                )

            # -------------------------------------------------
            # VALIDATE RESPONSE
            # -------------------------------------------------

            if not content:

                raise RuntimeError(
                    "Ollama returned an empty response."
                )

            return content

        except requests.exceptions.ConnectionError as exc:

            print(
                "AYRA OLLAMA ERROR: "
                "Could not connect to Ollama."
            )

            raise exc

        except requests.exceptions.Timeout as exc:

            print(
                "AYRA OLLAMA ERROR: "
                "Request timed out."
            )

            raise exc

        except requests.exceptions.HTTPError as exc:

            print(
                f"AYRA OLLAMA HTTP ERROR: "
                f"{response.status_code}"
            )

            try:
                print(
                    f"Response: {response.text}"
                )
            except Exception:
                pass

            raise exc

        except requests.exceptions.RequestException as exc:

            print(
                f"AYRA OLLAMA REQUEST ERROR: {exc}"
            )

            raise exc

        except ValueError as exc:

            print(
                "AYRA OLLAMA ERROR: "
                "Invalid JSON response."
            )

            raise exc

        except Exception as exc:

            print(
                f"AYRA OLLAMA ERROR "
                f"({type(exc).__name__}): {exc}"
            )

            raise exc